# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Cradio Dongle'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["cradio_left","cradio_right","cradio_dongle","settings_reset"]'
      custom_config: '["#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y"]'
